#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-ms-golden-copy.fullname" . }}
  labels:
  {{- include "eric-oss-ms-golden-copy.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-ms-golden-copy.annotations" . | nindent 4 }}
  {{- include "eric-oss-ms-golden-copy.prometheus" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-ms-golden-copy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
